linagora/esn-frontend-calendar

package.json
src/index.js
src/linagora.esn.calendar/app/app.js

This PR shows how to use the mailto handler from openpaas-suite/esn#3

openpaas-suite/esn#3 Add the mailto handler

---

src/app/app.config.js
src/app/app.js
src/app/app.run.js
src/index.js
src/linagora.esn.calendar/app/app.js
src/require-angular-injections.js

Do not require *.* from esn-frontend-common-libs
Closes #13

 #13 dependencies optimization

---

package.json
src/linagora.esn.calendar/images/calendar-icon.svg
webpack.commons.js

 #20 Favicon support

---

assets/index.pug
src/app/app-loading.pug
src/app/app.run.js

Closes #22
**Before**
**Splashscreen**

 #22 splashscreen support

---

src/linagora.esn.calendar/app/app.js

 #28 add angular-clockpicker angular dependency

---

src/linagora.esn.calendar/app/app.js
src/linagora.esn.calendar/app/routes.js

Fixes #12. Requires https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/74 to be merged first.
Demo:
[![Demo-Search-Back-Button-Fixed](https://user-images.githubusercontent.com/24670327/88646824-a14a8c80-d0ef-11ea-84f2-733b859adf2b.gif)
](https://streamable.com/obj975)

#12: Added missing dependency 'previous-page' and provided a default route state

---

.env.example
.gitignore
README.md
package.json
webpack.commons.js

Partiall resolves https://github.com/OpenPaaS-Suite/esn/issues/24.

esn#24: Brought the new application grid to Calendar SPA

---

src/linagora.esn.calendar/app/app.js
src/linagora.esn.calendar/app/routes.js
src/linagora.esn.calendar/app/settings/calendars/settings-calendars.component.js
src/linagora.esn.calendar/app/settings/calendars/settings-calendars.controller.js
src/linagora.esn.calendar/app/settings/display/settings-display.component.js
src/linagora.esn.calendar/app/settings/display/settings-display.controller.js
src/linagora.esn.calendar/app/settings/display/settings-display.pug
src/linagora.esn.calendar/app/settings/settings.controller.js
src/linagora.esn.calendar/app/settings/settings.pug

The detail in issue https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/42
It's better to check changes in each commit because there is one commit to remove IIFE that looks messy

#42 - Fix page Manage Calendars is broken

---

src/esn.calendar.libs/app/services/fullcalendar/render-event.service.js

Resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/54. Please also refer to https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/101.
- Before:
- After:

Now recurrent events with a small duration will also show the recurrence icons

---

package.json
src/linagora.esn.calendar/app/app.js
src/linagora.esn.calendar/app/settings/import/calendar-import.controller.js
src/linagora.esn.calendar/app/settings/import/calendar-import.controller.spec.js

#51 fix import calendar from file feature

---

Jenkinsfile
README.md
src/esn.calendar.libs/app/services/cal-ui-authorization-service.spec.js
test/Dockerfile
test/config/karma.conf.js

Partially resolve: https://github.com/OpenPaaS-Suite/esn/issues/29

OpenPaaS-Suite/esn#29 Setup CI

---

src/linagora.esn.calendar/app/components/calendar/calendar.controller.js

 #82 fix variable name

---

src/linagora.esn.calendar/app/settings/import/calendar-import.controller.js

 86 use location.origin for base_url

---

src/esn.calendar.libs/app/services/cal-ui-authorization-service.js
src/esn.calendar.libs/app/services/cal-ui-authorization-service.spec.js
webpack.commons.js

#85 Makes import from file feature works with my published calendar

---

package.json
src/app/app.js
webpack.commons.js
webpack.prod.js

 #91 calendar group resolver

---

src/linagora.esn.calendar/app/settings/settings.pug

closes https://github.com/OpenPaaS-Suite/esn/issues/35

OpenPaaS-Suite/esn#35 fix no animation

---

src/esn.calendar.libs/app/components/attendee/attendee-item-consult/attendee-item-consult.less
src/esn.calendar.libs/app/components/attendee/attendee-item/attendee-item.less
src/linagora.esn.calendar/app/components/event-participation/event-participation.less
src/linagora.esn.calendar/app/components/event-participation/event-participation.pug

- The fixing of the button mimic another button design inside calendar SPA having similar functionality, so that the UI is consistent throughout. 
**1. On Laptop**
**2. Responsive**

OpenPaaS-Suite/esn-frontend-calendar-public#17 Fix invitation page UI

---

src/esn.calendar.libs/app/app.module.js
src/esn.calendar.libs/app/components/event/form/event-form.pug

 #127 add auto-focus on event title

---

src/esn.calendar.libs/app/services/timezone.js
src/esn.calendar.libs/app/services/timezone.spec.js

Resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/119.

i#119: Added missing timezone support

---

src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.js
src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.less
src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.pug
src/linagora.esn.calendar/app/components/calendar-color-picker/calendar-color-picker.spec.js

#109 Add color picker when create new calendar

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js

#139 resolve undefined value of alarm after editing

---

Jenkinsfile
src/app/app.js

See also OpenPaaS-Suite/esn-frontend-group/pull/11
So not merge this one before having merged ^^

OpenPaaS-Suite/esn-frontend-group#7 Clean group import

---

test/Dockerfile

Partially resolves https://github.com/OpenPaaS-Suite/esn/issues/38.

esn#38: Fixed Firefox version for CI

---

package.json
src/esn.calendar.libs/app/components/event/form/event-form.directive.js
src/esn.calendar.libs/app/components/event/form/event-form.directive.spec.js
src/index.js
src/index.test.js

Fix: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/140

#140 Make dialog box draggable

---

src/esn.calendar.libs/app/app.module.js
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.controller.js
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.controller.spec.js
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.pug
src/esn.calendar.libs/app/components/time-select/time-select-menu-close.directive.js
src/esn.calendar.libs/app/components/time-select/time-select-scroll.directive.js
src/esn.calendar.libs/app/components/time-select/time-select.component.js
src/esn.calendar.libs/app/components/time-select/time-select.controller.js
src/esn.calendar.libs/app/components/time-select/time-select.controller.spec.js
src/esn.calendar.libs/app/components/time-select/time-select.pug
src/esn.calendar.libs/app/services/fc-moment.js

desktop demo: https://streamable.com/4j0z2y
mobile demo: https://streamable.com/n8paun

#98 add time select component

---

src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.pug
src/esn.calendar.libs/app/components/time-select/time-select.component.js
src/esn.calendar.libs/app/components/time-select/time-select.pug

demo: https://streamable.com/k5uif4

#184 disable the time select when the user can't modify the event

---

src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.controller.js
src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.pug

**DEMO**:
- in a normal event ( end and begin time ): https://streamable.com/wd4oqv
- in an all-day event: https://streamable.com/wpgzcm

#179 replace the clockpicker with time select component in time proposition

---

src/esn.calendar.libs/app/services/fullcalendar/planning-render-event.service.js
src/esn.calendar.libs/app/services/fullcalendar/planning-render-event.service.spec.js
src/linagora.esn.calendar/app/planning/calendar-planning.less

Fix: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/60

#60 Add style for event in planning section

---

src/esn.calendar.libs/app/components/time-select/time-select.controller.js
src/esn.calendar.libs/app/components/time-select/time-select.controller.spec.js

demo: https://streamable.com/q8npww

#181 fix time select not considering the locale correctly when setting the selected time

---

src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.controller.js
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.controller.spec.js
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.pug
src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.controller.js
src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.controller.spec.js
src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.pug

tested on android
event date edition / creation demo: https://streamable.com/6vl162
event date suggestion demo: https://streamable.com/ztgxh3

#98 use the native time picker when on mobile devices

---

src/esn.calendar.libs/i18n/en.json
src/esn.calendar.libs/i18n/fr.json
src/esn.calendar.libs/i18n/ru.json
src/esn.calendar.libs/i18n/vi.json
src/esn.calendar.libs/i18n/zh.json
src/linagora.esn.calendar/app/event-view/external-user/event-view-external-user.controller.js

#193 update message notification when action is updated

---

src/esn.calendar.libs/app/components/event/form/modals/edit-instance-or-series-modal.less

# fix size modal suggest form  on mobile screen

---

src/esn.calendar.libs/app/components/time-select/time-select.component.js

#184 fixed time select not being disabled when the user has no permission to edit the event

---

src/esn.calendar.libs/app/components/time-select/time-select-menu-close.directive.js
src/esn.calendar.libs/app/components/time-select/time-select-menu-close.directive.spec.js

**demo**: https://streamable.com/ttjofy

#98 close the time selector when the event form is dragged

---

src/esn.calendar.libs/i18n/vi.json

Resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/186.

#186 update private translation message in vi

---

src/esn.calendar.libs/app/components/event/form/event-form.pug

**demo**: https://streamable.com/duu0dm

#250 hide partstat buttons when duplicating an event

---

Dockerfile

related to https://github.com/OpenPaaS-Suite/openpaas-front/issues/2

Set up default values for BASE_HREF and APP_GRID_ITEMS

---

src/esn.calendar.libs/app/app.module.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js
src/esn.calendar.libs/app/services/event-duplicate.service.js
src/esn.calendar.libs/app/services/event-duplicate.service.spec.js

**demo**:
- duplicate an event from a non-default calendar https://streamable.com/rulxhl
- duplicate an event from a shared calendar https://streamable.com/8wt9ez

#247 default to the source calendar when duplicating an event if possible.

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js

#266: Allow delegated user to change participation when calendar owner is invited

---

src/esn.calendar.libs/app/app.module.js
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.controller.js
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.controller.spec.js
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.pug
src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.controller.js
src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.controller.spec.js
src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.pug
src/esn.calendar.libs/app/services/moment-date.service.js
src/esn.calendar.libs/app/services/moment-date.service.spec.js

demo: https://streamable.com/7tw6r0

#219 Use the native date picker in mobile devices

---

src/linagora.esn.calendar/app/planning/calendar-planning.controller.js
src/linagora.esn.calendar/app/planning/calendar-planning.controller.spec.js

demo: https://streamable.com/1zvxzi

#229 hide events from the planning view if the source calendar is hidden

---

src/linagora.esn.calendar/app/calendar/calendar-view/calendar-view.controller.js
src/linagora.esn.calendar/app/calendar/calendar-view/calendar-view.controller.spec.js

**demo**: https://streamable.com/rc36nn

#273 fixed event alarm being lost when dragging & dropping an event

---

src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-main/calendar-configuration-tab-main.controller.js
src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-main/calendar-configuration-tab-main.controller.spec.js

**demo**: https://streamable.com/p0j8wq

#290 fix the calendar export

---

src/esn.calendar.libs/app/app.constants.js
src/esn.calendar.libs/app/components/freebusy/freebusy.service.spec.js
src/esn.calendar.libs/app/components/partstat-buttons/partstat-buttons.controller.spec.js
src/esn.calendar.libs/app/services/calendar-api.js
src/esn.calendar.libs/app/services/calendar-api.spec.js
src/esn.calendar.libs/app/services/calendar-service.js
src/esn.calendar.libs/app/services/calendar-service.spec.js
src/esn.calendar.libs/app/services/event-service.spec.js
src/esn.calendar.libs/app/services/shells/calendar-shell.spec.js
src/linagora.esn.calendar/app/app.js
src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-main/calendar-configuration-tab-main.controller.js
src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-main/calendar-configuration-tab-main.controller.spec.js
src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-main/calendar-configuration-tab-main.pug

**demo**: https://streamable.com/2b5l51

#290 use the calDavRequest to export a calendar

---

src/esn.calendar.libs/app/components/event-date-suggestion/modal/event-date-suggestion-modal.service.js

**demo**: https://streamable.com/3xbwb2

#254 fixed the propose a new time option in bluebar not showing up

---

src/linagora.esn.calendar/app/routes.js
src/linagora.esn.calendar/app/settings/calendars/settings-calendars.pug

Fix: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/147

#147 Fix Shared calendar dialog box

---

src/esn.calendar.libs/app/app.run.js
src/linagora.esn.calendar/app/run.js

#316: Added missing cache for templates via templateCache

---

src/esn.calendar.libs/app/components/event-alarm-edition/event-alarm-edition.pug
src/esn.calendar.libs/app/components/event-recurrence-edition/event-recurrence-edition.pug
src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.less
src/esn.calendar.libs/app/components/event/form/event-form.pug

Fix: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/313

#313 Fix dropdown in event dialog

---

src/linagora.esn.calendar/app/calendar-shared-configuration/calendar-shared-configuration.less
src/linagora.esn.calendar/app/calendar-shared-configuration/calendar-shared-configuration.pug
src/linagora.esn.calendar/app/calendar-shared-configuration/item/calendar-shared-configuration-item.less
src/linagora.esn.calendar/app/calendar-shared-configuration/item/calendar-shared-configuration-item.pug

Fix: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/322

#322 Add calendar picker when adding shared calendar

---

src/esn.calendar.libs/app/components/event-recurrence-edition/event-recurrence-edition.js
src/esn.calendar.libs/app/components/event-recurrence-edition/event-recurrence-edition.spec.js

DEMO :https://streamable.com/w5yxn0

#320 test setDefaultUntilDate when canMOdifyEvent is false

---

src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-main/calendar-configuration-tab-main.controller.js
src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-main/calendar-configuration-tab-main.controller.spec.js
src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-main/calendar-configuration-tab-main.pug

**demo**: https://streamable.com/6o8haf

#332 only show the secret address generation option when editing a calendar

---

src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration.controller.js
src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration.controller.spec.js

**demo**: https://streamable.com/shg1rr

#294 fixed special characters being encoded in the notification messages

---

src/esn.calendar.libs/i18n/en.json
src/esn.calendar.libs/i18n/fr.json
src/esn.calendar.libs/i18n/ru.json
src/esn.calendar.libs/i18n/vi.json
src/esn.calendar.libs/i18n/zh.json

#336 add translation text for adding shared calendar

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js
src/esn.calendar.libs/app/components/event/form/event-form.pug
src/esn.calendar.libs/i18n/en.json
src/esn.calendar.libs/i18n/fr.json
src/esn.calendar.libs/i18n/ru.json
src/esn.calendar.libs/i18n/vi.json
src/esn.calendar.libs/i18n/zh.json

https://user-images.githubusercontent.com/43316837/102887034-77a35080-4456-11eb-8d2e-74b9aefcfeb2.mp4

#341 open location in new window if it is a link

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js

https://user-images.githubusercontent.com/6764881/103796594-b4bb3580-5047-11eb-9d33-621ffedda57a.mp4

#297 fixed duplicate events not having alarms after creation

---

src/esn.calendar.libs/app/components/event/form/event-form.less

Resolves https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/213.

esn-frontend-inbox#213: Now the CSS applied to the event dialog is scoped correctly

---

src/esn.calendar.libs/app/components/time-select/time-select.controller.js
src/esn.calendar.libs/app/components/time-select/time-select.controller.spec.js
src/esn.calendar.libs/app/services/fc-moment.js
src/linagora.esn.calendar/app/search/event/event-search-card.component.spec.js

https://user-images.githubusercontent.com/6764881/103880260-2becda00-50d9-11eb-8b64-5f22dd427efc.mp4

#160 fixed the Chinese locale not working with the time-select component

---

src/esn.calendar.libs/app/app.constants.js

https://user-images.githubusercontent.com/43316837/105052559-50996800-5a70-11eb-97fa-3f5530a4f451.mp4

#350 configure weekNumberCalculation to work with ISO method

---

src/linagora.esn.calendar/app/calendar/calendar-header/calendar-sub-header.pug

#382: Repositioned the button to refresh calendar

---

src/esn.calendar.libs/i18n/en.json
src/esn.calendar.libs/i18n/fr.json
src/esn.calendar.libs/i18n/ru.json
src/esn.calendar.libs/i18n/vi.json
src/esn.calendar.libs/i18n/zh.json
src/linagora.esn.calendar/app/components/show-main-sidebar-button/show-main-sidebar-button.pug

Resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/396.

#396: Added tooltip to the toggle sidebar button

---

src/linagora.esn.calendar/app/routes.js

https://user-images.githubusercontent.com/6764881/105828752-cac37280-5fc3-11eb-9586-d33daf35b096.mp4

#226 fixed calendar logo not redirecting back to the main calendar page

---

src/esn.calendar.libs/app/components/event-recurrence-edition/event-recurrence-edition.js
src/esn.calendar.libs/app/components/event-recurrence-edition/event-recurrence-edition.pug
src/esn.calendar.libs/app/components/event-recurrence-edition/event-recurrence-edition.spec.js

demo: https://streamable.com/81udbb

#395 use the native mobile picker when selecting the until date for recurrent events

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js
src/esn.calendar.libs/app/components/event/form/event-form.pug

**DEMO:**
https://user-images.githubusercontent.com/43316837/105866415-3faea080-5ff4-11eb-9b26-55b2b64c65e3.mp4

#406 update location link when it does not start with http

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js
src/esn.calendar.libs/app/components/event/form/event-form.directive.spec.js
src/esn.calendar.libs/app/components/mail-to-attendees/mail-to-attendees.controller.js
src/esn.calendar.libs/app/components/mail-to-attendees/mail-to-attendees.controller.spec.js
src/esn.calendar.libs/app/components/mail-to-attendees/mail-to-attendees.pug
src/esn.calendar.libs/app/services/event-duplicate.service.js
src/esn.calendar.libs/app/services/event-duplicate.service.spec.js
src/esn.calendar.libs/app/services/event-utils.js
src/esn.calendar.libs/app/services/event-utils.spec.js

Partially resolves #412. Please also refer to https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/167.

#412: Refactored some parts of the code in Event Form Controller

---

src/esn.calendar.libs/app/services/cached-event-source.js
src/esn.calendar.libs/app/services/cached-event-source.spec.js

https://user-images.githubusercontent.com/43316837/105485631-80817f00-5cad-11eb-9b18-baf1eeb90234.mp4

#385 dont hide declined event  in the main calendar

---

src/esn.calendar.libs/app/components/event-alarm-edition/event-alarm-edition.pug
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.less
src/esn.calendar.libs/app/components/event-date-edition/event-date-edition.pug
src/esn.calendar.libs/app/components/event-recurrence-edition/event-recurrence-edition.pug
src/esn.calendar.libs/app/components/event/form/event-form.less
src/esn.calendar.libs/app/components/event/form/event-form.pug
src/esn.calendar.libs/i18n/en.json
src/esn.calendar.libs/i18n/fr.json
src/esn.calendar.libs/i18n/ru.json
src/esn.calendar.libs/i18n/vi.json
src/esn.calendar.libs/i18n/zh.json

Resolves #348. Please also refer to https://github.com/OpenPaaS-Suite/esn-frontend-videoconference-calendar/pull/14.
- Demo (Desktop):
https://user-images.githubusercontent.com/24670327/106874895-ade81700-6708-11eb-84c5-be3336962656.mp4
- Demo (Mobile):

#348: Added event form collapsibility

---

src/esn.calendar.libs/app/services/cached-event-source.js
src/esn.calendar.libs/app/services/cached-event-source.spec.js

**TO DO:** 
**DEMO**
https://user-images.githubusercontent.com/43316837/106864665-7d818800-66ca-11eb-877d-7c790dce3f84.mp4

#388 disable editable field to attendee

---

src/linagora.esn.calendar/app/calendar/calendar-view/calendar-view.controller.js
src/linagora.esn.calendar/app/calendar/calendar-view/calendar-view.controller.spec.js
src/linagora.esn.calendar/app/planning/calendar-planning.controller.js
src/linagora.esn.calendar/app/planning/calendar-planning.controller.spec.js

**DEMO: (for view calendar)**
https://user-images.githubusercontent.com/43316837/107039354-19d88700-67be-11eb-9d25-ad019ba9f55a.mp4
**DEMO :(for planning)**
https://user-images.githubusercontent.com/43316837/107700559-efa03100-6cb7-11eb-9b54-0855db824d5e.mp4

#393 test if calendar is not hidden in update action

---

src/linagora.esn.calendar/app/search/event/event-search.less

#359 fixed event search item not displaying nicely

---

src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-delegation/calendar-configuration-tab-delegation.pug

https://user-images.githubusercontent.com/6764881/108965902-c69b7b00-767d-11eb-9f48-c973d3c486d9.mp4

#419 fixed the calendar configuration delegation tab closing when clicking on the add button

---

src/esn.calendar.libs/app/components/event/form/event-form.pug

https://user-images.githubusercontent.com/6764881/108999538-bba71180-76a2-11eb-91c7-c2148331b758.mp4

#422 replaced event form duplicate and delete button titles with tooltips

---

src/linagora.esn.calendar/app/calendar/calendar-view/calendar-view.controller.js
src/linagora.esn.calendar/app/calendar/calendar-view/calendar-view.controller.spec.js

#371: Now the event dialog is opened instead of the event preview popover when an event is clicked in mobile devices

---

src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.less
src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.pug

Continues to resolve #371.
- Before:
- After:

#371: Fixed a minor UI issue with the event description

---

webpack.commons.js

calendar SPA console:
production build:

#453 added env/openpaas.js file and excluded it from the webpack bundle

---

src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.controller.js
src/esn.calendar.libs/app/components/event-date-suggestion/event-date-suggestion.pug

https://user-images.githubusercontent.com/6764881/110810650-4a608480-8286-11eb-9917-485e737c8b0e.mp4

#265 fixed the propose new time date selector not displaying starting from the end date month

---

src/linagora.esn.calendar/app/settings/calendars/settings-calendars.pug
src/linagora.esn.calendar/app/settings/settings.less
src/linagora.esn.calendar/app/settings/settings.pug

Resolves #391.
- Before:
- After:

#391: Fixed a bug where the fab button in calendar settings is partially hidden in Safari

---

src/esn.calendar.libs/app/components/event/form/event-form.less

Resolves #487 once and for all.

#487: Fixed an issue where the last field in the event form is not shown fully in Safari

---

src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.controller.js
src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.controller.spec.js

#507: Fixed a bug where the event preview popover does not display attendees' avatars

---

src/esn.calendar.libs/app/components/entities-autocomplete-input/entities-autocomplete-input.less

fixed attendees box

---

package.json
src/linagora.esn.calendar/app/calendar/calendar-header/calendar-sub-header.controller.js
src/linagora.esn.calendar/app/calendar/calendar-header/calendar-sub-header.less

Continues to resolve https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/499.

esn-frontend-calendar#499: Adopted the new way we mount the new Vue component

---

src/esn.calendar.libs/app/components/attendee/attendee-item/attendee-item.component.js
src/esn.calendar.libs/app/components/attendee/attendee-item/attendee-item.pug
src/esn.calendar.libs/app/components/attendee/list/attendee-list.component.js
src/esn.calendar.libs/app/components/attendee/list/attendee-list.pug
src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.pug
src/esn.calendar.libs/app/components/event/form/event-form.pug
src/esn.calendar.libs/app/components/mail-to-attendees/mail-to-attendees.pug

RELATED PR :
https://github.com/linagora/esn-frontend-mailto-handler/pull/11
https://github.com/linagora/esn-frontend-mailto/pull/70
DEMO : 
https://user-images.githubusercontent.com/43316837/117742115-e4e43200-b1fb-11eb-8730-37cb0cfe80a0.mp4

#532 add event title to email subject

---

nginx.conf
src/app/app.config.js
webpack.commons.js

Test are not failing on my env

use html5 history to remove hash on urls

---

src/esn.calendar.libs/app/app.constants.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.pug
src/esn.calendar.libs/app/services/shells/calendar-shell.js
src/esn.calendar.libs/app/services/shells/calendar-shell.spec.js

related to https://github.com/linagora/esn-frontend-calendar/issues/613
https://user-images.githubusercontent.com/6764881/141692016-07471bcf-4bb2-48d9-8fe7-8c330713c0d1.mp4

#613 set user availability when creating an event

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js
src/esn.calendar.libs/app/components/event/form/event-form.pug
src/esn.calendar.libs/app/services/calendar-api.js
src/esn.calendar.libs/app/services/calendar-api.spec.js
src/esn.calendar.libs/app/services/event-service.js
src/esn.calendar.libs/app/services/event-service.spec.js

Reverts linagora/esn-frontend-calendar#618

Revert "linagora/esn-frontend-calendar#611 move events between calendars"

---

src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.pug

Fix wrong organizer name on event preview popover

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js
src/esn.calendar.libs/app/components/event/form/event-form.pug
src/esn.calendar.libs/app/services/calendar-api.js
src/esn.calendar.libs/app/services/calendar-api.spec.js
src/esn.calendar.libs/app/services/event-service.js
src/esn.calendar.libs/app/services/event-service.spec.js

https://user-images.githubusercontent.com/6764881/145413764-eae460bf-e99e-4575-b4ec-2060a4f34af5.mp4

linagora/esn-frontend-calendar#611 move events between calendars #618

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js

related to: https://github.com/linagora/esn-frontend-calendar/issues/611
https://user-images.githubusercontent.com/6764881/155670473-d4a64134-4f2a-4a39-a284-917de6d4b4fb.mp4

fixed read only delegated users not being able to open events

---

src/esn.calendar.libs/app/components/freebusy/freebusy-api.service.spec.js
src/esn.calendar.libs/app/components/freebusy/freebusy.service.spec.js
src/esn.calendar.libs/app/services/calendar-api.spec.js
src/esn.calendar.libs/app/services/calendar-event-source.spec.js
src/esn.calendar.libs/app/services/calendar-service.spec.js
src/esn.calendar.libs/app/services/calendar-subscription-api.service.spec.js
src/esn.calendar.libs/app/services/dav-request.spec.js
src/esn.calendar.libs/app/services/event-api.spec.js
src/esn.calendar.libs/app/services/event-service.spec.js

closes https://github.com/linagora/esn-frontend-common-libs/issues/262

linagora/esn-frontend-common-libs#262 removed tokenAPI esntoken dependency

---

src/linagora.esn.calendar/app/components/calendars-list/items/item/calendars-list-item.less

#644 fixed calendar settings dots not being aligned properly
