linagora/esn-frontend-calendar

src/linagora.esn.calendar/app/calendar/calendar-header/calendar-sub-header.less

esn-frontend-calendar#19: Fixed broken subheader UI in mobile

---

src/esn.calendar.libs/app/app.module.js
src/linagora.esn.calendar/app/app.js

calendar.libs will be used with `esn-frontend-libs` so it has no use for mailto-handler
resolves https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/122

OpenPaaS-Suite/esn-frontend-inbox#122 moved the mailto-handler dependency outide of calendar.libs

---

src/linagora.esn.calendar/app/app.js
src/linagora.esn.calendar/app/settings/import/calendar-import.controller.js

Partially resolves https://github.com/OpenPaaS-Suite/esn-dav-import-client/issues/5. Please also refer to https://github.com/OpenPaaS-Suite/esn-dav-import-client/pull/6.

esn-dav-import-client#5: Adjusted the way ESNDavImportClient is constructed to use only a single instance of Client

---

src/esn.calendar.libs/app/components/event/form/event-form.pug

#155 The Attendees and Resources fields now follow the date/time field

---

package.json
src/esn.calendar.libs/app/components/event/form/event-form.directive.js
src/esn.calendar.libs/app/components/event/form/event-form.directive.spec.js
src/index.js
src/index.test.js

Reverts OpenPaaS-Suite/esn-frontend-calendar#151.
Reasons:
- The modal body is also draggable, which causes issues with the dropdowns inside the body. For example, you cannot select the options from the autocomplete dropdowns ("Attendees", "Resources", etc.).
- It breaks the event dialog completely in mobile devices.

Revert "#140 Make dialog box draggable"

---

src/esn.calendar.libs/app/components/event/form/event-form.less
src/esn.calendar.libs/app/components/event/form/event-form.pug

Resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/188.
Demo:

esn-frontend-calendar#188: Now the resource autocomplete dropdown is no longer overlapped by the fields below

---

src/esn.calendar.libs/app/components/time-select/time-select.controller.js
src/esn.calendar.libs/app/components/time-select/time-select.controller.spec.js
src/esn.calendar.libs/app/components/time-select/time-select.pug

demo: https://streamable.com/sm7cv1
updated demo: https://streamable.com/43f4u5
Continues to resolve https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/98.

#98 close the time selector when the user switches between inputs with tab

---

src/esn.calendar.libs/app/services/event-service.js
src/esn.calendar.libs/app/services/event-service.spec.js

Continues to resolve https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/168.

esn-frontend-calendar#168: The error notifications when performing actions on an event will no longer display unnecessary status text to the user

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js
src/esn.calendar.libs/app/services/event-service.js
src/esn.calendar.libs/app/services/event-service.spec.js
src/esn.calendar.libs/i18n/en.json
src/esn.calendar.libs/i18n/fr.json
src/esn.calendar.libs/i18n/ru.json
src/esn.calendar.libs/i18n/vi.json
src/esn.calendar.libs/i18n/zh.json

Continues to resolve https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/168.
- Demo:
[![Demo-Event-Update-Notification](https://user-images.githubusercontent.com/24670327/96209281-6a22a380-0f99-11eb-89ca-6fc80510db6e.gif)](https://streamable.com/5xzep7)

esn-frontend-calendar#168: Now the notifcation when saving an event will be closed when there is an error while saving the event

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js
src/esn.calendar.libs/app/services/event-service.js
src/esn.calendar.libs/app/services/event-service.spec.js

**DEMOS**:
edit the organizer participation without saving the form: https://streamable.com/rq9hal
edit the organizer participation  and continue editing and saving the form: https://streamable.com/2n9wpy
edit organizer participation with recurrent events: https://streamable.com/upxz50
disable action forms while updating the partstat: https://streamable.com/l88g6l

#89 allow event organizer to update the event participation status without saving the form

---

src/esn.calendar.libs/app/services/event-service.js
src/esn.calendar.libs/app/services/event-service.spec.js
src/linagora.esn.calendar/app/routes.js

**Demo**: https://streamable.com/aujioy
**Backend PR** :https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.calendar/merge_requests/686
**Flow Chart of invite user (internal and external)** 
When an orgonizer create an event and invite a list of attendee , an email will be sent with the details of invitation and generate links  for each actions depending of type of the attendee
**External Attendee**
Links action will be generated with excal 
Each action redirect to EXCAL app (calendar public SPA)
**Internal User**
Links action will be generated with calendar
Each action redirect to Calendar app with new state called participation (with event id)
When the application redirect to participation state  , the modal of detail event will be opened

 #216 redirect internal user to event detail when he change participation from link in email invitation

---

package.json
src/esn.calendar.libs/app/app.module.js
src/esn.calendar.libs/app/services/event-service.js
src/esn.calendar.libs/app/services/event-service.spec.js
src/esn.calendar.libs/app/services/partstat-jwt.service.js
src/esn.calendar.libs/app/services/partstat-jwt.service.spec.js
src/esn.calendar.libs/i18n/en.json
src/esn.calendar.libs/i18n/fr.json
src/esn.calendar.libs/i18n/ru.json
src/esn.calendar.libs/i18n/vi.json
src/esn.calendar.libs/i18n/zh.json
src/linagora.esn.calendar/app/routes.js

Continues to resolve https://github.com/OpenPaaS-Suite/esn-frontend-calendar-public/issues/20.
- Demo: https://streamable.com/qrtm51

esn-frontend-calendar-public#20: Refactored the code to change participation status using jwt for internal users

---

webpack.commons.js

Context: We need these assets to have the same names each time we build the app so that we can load them in https://github.com/OpenPaaS-Suite/openpaas-gatling. I think this should be OK. Those are the assets that we do not frequently update so it's perfectly fine not to have a hash for them. Even if we have a problem with the browser's cache, it should not affect much (as long as the JavaScript files get updated).

Static assets now have static names

---

src/linagora.esn.calendar/app/calendar-configuration/calendar-configuration-tab-main/calendar-configuration-tab-main.pug

this click handler was deleted [here](https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/287/files#diff-20bf20087621db232e62e2ad73cf234af6c3664beafd543e1656f18ec4ef05f2L63)

#147 fixed export calendar button not working

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js

when opening an event with weird alarm:
```js
Error: invalid alarm set value, missing trigger or attendee
at y.set alarm [as alarm] (calendar-shell.js:445)
at n (event-form.controller.js:164)
at n.s.initFormData (event-form.controller.js:144)
at s (event-form.controller.js:97)
at Object.s [as invoke] (angular.js:4219)
```

fixed failing to open the event when the alarm has no attendee

---

src/esn.calendar.libs/app/components/select-calendar/select-calendar-item.less

#343 fixed shared calendars names with edit permission colliding with each other when selecting a calendar

---

src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.pug

#371: Now the event preview popover displays properly for an event with no title/summary

---

src/esn.calendar.libs/app/components/event/form/event-form.less

Resolves #456.
- Before:
- After:

#456: Now the footer of the event dialog is displayed properly in mobile devices

---

src/esn.calendar.libs/app/components/event/form/event-form.less

Resolves #306.
- Before:
- After:

#306: Now the description field is not cropped in mobile devices

---

src/esn.calendar.libs/app/components/event/form/event-form.less

Resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/487.
- Before:
- After:

esn-frontend-calendar#487: Fixed an issue where the last field in the event form is not shown fully in Safari

---

src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.component.js
src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.controller.js
src/esn.calendar.libs/app/components/event-preview-popover/event-preview-popover.controller.spec.js
src/esn.calendar.libs/app/services/event-preview-popover.service.js
src/esn.calendar.libs/app/services/event-preview-popover.service.spec.js
src/linagora.esn.calendar/app/calendar/calendar-view/calendar-view.controller.js
src/linagora.esn.calendar/app/calendar/calendar-view/calendar-view.controller.spec.js

#508: Fixed an issue where the event preview popover displays the incorrect name and color of a publicly shared calendar

---

src/esn.calendar.libs/app/app.module.js
src/esn.calendar.libs/app/components/event/form/open/open-event-from-search-form.service.spec.js
src/esn.calendar.libs/app/components/partstat-buttons/partstat-buttons.controller.spec.js
src/esn.calendar.libs/app/services/event-duplicate.service.spec.js
src/esn.calendar.libs/app/services/event-service.spec.js
src/esn.calendar.libs/app/services/event-utils.spec.js
src/esn.calendar.libs/app/services/fc-moment.spec.js
src/esn.calendar.libs/app/services/master-event-cache.spec.js
src/esn.calendar.libs/app/services/shells/calendar-shell.js
src/esn.calendar.libs/app/services/shells/calendar-shell.spec.js
src/index.test.js
src/linagora.esn.calendar/app/app.js
src/linagora.esn.calendar/app/components/event-alarm-consultation/event-alarm-consultation.controller.spec.js
src/linagora.esn.calendar/app/components/event-date-consultation/event-date-consultation.controller.spec.js
webpack.commons.js

Fixes invalid ICS
TIMEZONE now matches DTSTART adn DTEND timezone
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.3//EN
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VTIMEZONE
TZID:Europe/Paris
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
UID:2493c80c-12bc-4662-ac7d-3512342bb80f
TRANSP:OPAQUE
DTSTART;TZID=Europe/Paris:20210710T133000
DTEND;TZID=Europe/Paris:20210710T150000
CLASS:PUBLIC
X-OPENPAAS-VIDEOCONFERENCE:
SUMMARY:
ORGANIZER;CN=user@open-paas.org:mailto:user@open-paas.org …
```

#594: Fix ICS TIMEZONE

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.controller.spec.js
src/esn.calendar.libs/app/components/event/form/event-form.pug
src/esn.calendar.libs/app/services/cal-ui-authorization-service.js
src/esn.calendar.libs/app/services/cal-ui-authorization-service.spec.js

Introduce a canMoveEvent UI authorization to handle specific authorization that don't match canModifyEvent
For now only calendar owner can move an event.

#611 Fix event move

---

src/esn.calendar.libs/app/components/event/form/event-form.controller.js
src/esn.calendar.libs/app/components/event/form/event-form.pug
src/esn.calendar.libs/app/services/cal-ui-authorization-service.js
src/esn.calendar.libs/app/services/cal-ui-authorization-service.spec.js

Fix 2 issues
* If event cannot be modified, calendar select is still active.
* When calendar is shared in read only, event calendar is not properly displayed

Fix calendar display in read only calendar
